---
title: "Tabela de Counts"
author: "Marcella Belém"
date: "2024-09-07"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(dplyr)
```

#TABELA DE COUNTs
```{r}
#1- organização dos arquivos individuais, somandos os genes_id iguais
input_directory <- "C:/Users/Reis/OneDrive/bio e/MCI/newcounts"

# Listar todos os arquivos de contagem
count_files <- list.files(path = input_directory, pattern = "*_counts.txt", full.names = TRUE)

data=read.table("counts/SRR10015384_counts.txt", sep= "")

```
#Processamento de cada arquivo de contagem da amostra, para limpeza do arquivo e uniformização


```{r, echo = TRUE, results = 'hide'}
# Loop para processar cada arquivo individual de count gerado pelo htseq-count
#fill = TRUE permite que o R preencha as linhas curtas com NA para garantir que todas tenham o mesmo número de colunas.


for (file in count_files) {
  # Ler o arquivo em um data frame
  df <- read.table(file, header = FALSE, sep = "\t", col.names = c("gene_id","gene_name","count"), fill= TRUE)
  
  
  #colocar a coluna counts com valores numéricos
  df$count <- as.numeric(df$count)
  
  # Agrupar por 'gene_id' e somar os 'counts
  df_sum <- df %>% group_by(gene_id, gene_name) %>%
    summarise(total_count = sum(count), .groups = 'drop')
  #remove as linhas de estatisticas
   df_sum <- df_sum %>% filter(!grepl("__", gene_id))
  

  # Salvar o resultado no mesmo diretório com o mesmo nome (sobreescreve o original)
  write.table(df_sum, file = file, sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
}
```

#criação de uma única tabela de counts
```{r, echo = TRUE, results = 'hide'}
#2- combinar todas os arquivos em uma unica tabela de counts
#Listar todos os arquivos de contagem
new_count_files <- list.files(path = input_directory, pattern = "*_counts.txt", full.names = TRUE)

# Ler todos os arquivos de contagem em uma lista de DataFrames, add o nome da amostra para cada data frame de contagem

df_list <- lapply(new_count_files, function(file) {
  counts <- read.table(file, header = FALSE, sep = "\t")
  # Extrair o nome da amostra do arquivo (remover o caminho e a extensão '_counts.txt')
  sample_name <- gsub("_counts.txt$", "", basename(file))
  colnames(counts) <- c("gene_id", "gene_name", sample_name)
  counts <- counts[!grepl("^__", counts$gene_id), ] # Remover linhas de estatísticas que começam com '__'
})
  #reservar a coluna gene_name
  id_columns <- df_list[[1]][, c("gene_id", "gene_name")]

  # Remover a coluna 'gene_name' dos DataFrames, mantendo apenas 'gene_id' e os 'counts'
  df_list <- lapply(df_list, function(df) df[, c(1,3)])


```

```{r, echo = TRUE, results = 'hide'}
# Mesclar todos os DataFrames por 'gene_id'
counts_unico <- Reduce(function(x, y) merge(x, y, by = "gene_id", all = TRUE), df_list)
#add a coluna dos gene_name
counts_unico <- merge(id_columns, counts_unico, by = "gene_id")
# Salvar a tabela combinada
write.table(counts_unico, "tabela_counts164_new.csv", sep = "\t", row.names = FALSE, quote = FALSE)

#ler a tabela de counts unica criada para o dataset de 164 amostras
counts=read.csv("tabela_counts164.csv", sep= "\t", header= TRUE)



```
PREPARAR CADA GRUPO DO DATASET
```{r}
##NAO È NECESSARIO
#separar os counts por grupo CN, MCI e DA
#abrir dados clinicos e a tabela de coounts total
dados_clinicos=read.delim2("dados_clinicos_164_plus.csv", sep=",")
counts <- read.csv("tabela_counts164.csv", sep='\t', header=TRUE)
tcount=t(counts)
colnames(tcount) <- tcount[1, ]
tcount <- tcount[-1, ]

# Corrigir os nomes das colunas para combinar com os dados clínicos
tcount <- as.data.frame(tcount)
tcount$Run <- rownames(tcount)

# Mesclar os dados clínicos com a tabela de counts
merged_data <- merge(dados_clinicos, tcount, by.x="Run", by.y="Run")
write.table(merged_data, "counts_raw_data.csv", sep="\t")
counts2= read.csv("counts_raw_data.csv", sep= "\t", header= TRUE)


df_long <- counts2 %>%
  pivot_longer(
    cols = starts_with("ENSG00000"),  # Colunas de contagem (genes)
    names_to = "gene_id",        # Nome da nova coluna com os IDs dos genes
    values_to = "count"          # Nome da nova coluna com os valores de contagem
  )


df_long_unique <- df_long %>% distinct(Run, gene_id, count)

df_counts <- df_long_unique %>%
  select(gene_id, Run, count, AGE, SEX) %>%  # Selecionar apenas as colunas relevantes
  pivot_wider(
    names_from = Run,  # Converter as amostras em colunas
    values_from = count,     # Valores de contagem
    values_fill = list(count = 0)
  )

write.table(df_counts, "counts_tab_age_sex.csv", sep="\t")

````

````{r}
#separar os grupos
cn= dados_clinicos[dados_clinicos$GROUP == "CN", ]
cn=merge(tcount,cn, by.x= "Run", by.y="Run", all=FALSE)

mci= dados_clinicos[dados_clinicos$GROUP == "MCI", ]
mci=merge(tcount,mci, by.x= "Run", by.y="Run", all=FALSE)

ad= dados_clinicos[dados_clinicos$GROUP == "AD", ]
ad=merge(tcount,ad, by.x= "Run", by.y="Run", all=FALSE)


# Salvando os DataFrames em arquivos separados (opcional)
write.csv(cn, "counts_CN_164.csv", row.names=FALSE)
write.csv(mci, "counts_MCI_164.csv", row.names=FALSE)
write.csv(ad, "counts_DA_164.csv", row.names=FALSE)
````


